version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Clear pip cache
          command: pip cache purge
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest --cov=myapp tests/
