version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.10  # Оновлюємо Python до 3.10
    working_directory: ~/repo

jobs:
  install_dependencies:
    executor: python-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Install dependencies
          command: |
            python -m venv .venv
            . .venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            pip install pre-commit flake8 black isort pytest
      - save_cache:
          paths:
            - .venv
          key: dependencies-{{ checksum "requirements.txt" }}

  lint_code:
    executor: python-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Lint with pre-commit
          command: |
            . .venv/bin/activate
            pre-commit install
            pre-commit run --all-files

  run_tests:
    executor: python-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Run tests
          command: |
            . .venv/bin/activate
            pytest

workflows:
  version: 2
  ci_pipeline:
    jobs:
      - install_dependencies
      - lint_code:
          requires:
            - install_dependencies
      - run_tests:
          requires:
            - install_dependencies
